package com.att.training.diffblue;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.anyInt;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.Test;

/**
 * This test was generated by the Dcover cli (2021.06.01-21cddf2) using the following command:<br>
 * {@code dcover create --class-name-template='${CLASS_NAME}DcoverTest' --skip-test-validation}
 * {@link CalculatorController} is a Spring Controller, it makes no sense whatsoever to test it as a POJO.
 * Another minor issue: tests are generated with an indentation of 2 spaces, while the project uses 4.
 */
public class CalculatorControllerDcoverTest {
  @Test
  public void testAdd() {
    // Arrange, Act and Assert
    assertEquals(5, (new CalculatorController(new Calculator())).add(2, 3));
  }

  @Test
  public void testAdd2() {
    // Arrange
    Calculator calculator = mock(Calculator.class);
    when(calculator.add(anyInt(), anyInt())).thenReturn(2);

    // Act and Assert
    assertEquals(2, (new CalculatorController(calculator)).add(2, 3));
    verify(calculator).add(anyInt(), anyInt());
  }

  @Test
  public void testAbs() {
    // Arrange, Act and Assert
    assertEquals(42, (new CalculatorController(new Calculator())).abs(42));
    assertEquals(1, (new CalculatorController(new Calculator())).abs(-1));
  }

  @Test
  public void testAbs2() {
    // Arrange
    Calculator calculator = mock(Calculator.class);
    when(calculator.abs(anyInt())).thenReturn(1);

    // Act and Assert
    assertEquals(1, (new CalculatorController(calculator)).abs(42));
    verify(calculator).abs(anyInt());
  }
}

