package com.att.training.diffblue;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

/**
 * This class we generated by jcover (v0.7 3ffd6536) using the following command: <br>
 * {@code jcover --test-verification --no-factory-tests --use-var --assertj --class-suffix 'JcoverTest'}
 * <br>
 * Unit tests for com.att.training.diffblue.Calculator
 *
 * @author Diffblue Cover
 */

@ContextConfiguration(classes = {Calculator.class})
@ExtendWith(SpringExtension.class)
class CalculatorJcoverTest {

    @Autowired
    private Calculator service;

    @Test
    void add() {
        assertThat(service.add(-1, 1)).isEqualTo(0);
        assertThat(service.add(0, 1)).isEqualTo(1);
    }

    @Test
    void abs() {
        assertThat(service.abs(-1)).isEqualTo(1);
        assertThat(service.abs(1)).isEqualTo(1);
        assertThat(service.abs(0)).isEqualTo(0);
    }

    @Test
    void increment() {
        assertThat(service.increment(-1)).isEqualTo(0);
        assertThat(service.increment(0)).isEqualTo(1);
    }

    @Test
    void decrement() {
        assertThat(service.decrement(1)).isEqualTo(0);
        assertThat(service.decrement(0)).isEqualTo(-1);
    }

    @Test
    void addAndSet1() {
        var repository = mock(Repository.class);
        assertThat(service.addAndSet(-1, 1, repository)).isEqualTo(0);
        Mockito.verify(repository).setResult(Mockito.eq((Integer) 0));
    }

    @Test
    void addAndSet2() {
        var repository = mock(Repository.class);
        assertThat(service.addAndSet(0, 1, repository)).isEqualTo(1);
        Mockito.verify(repository).setResult(Mockito.eq((Integer) 1));
    }
}
